# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/i82dianr/DDimage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/i82dianr/DDimage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i82dianr/DDimage/CMakeFiles /home/i82dianr/DDimage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/i82dianr/DDimage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DDimage

# Build rule for target.
DDimage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DDimage
.PHONY : DDimage

# fast build rule for target.
DDimage/fast:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/build
.PHONY : DDimage/fast

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/common.cpp.s
.PHONY : common.cpp.s

compare.o: compare.cpp.o

.PHONY : compare.o

# target to build an object file
compare.cpp.o:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/compare.cpp.o
.PHONY : compare.cpp.o

compare.i: compare.cpp.i

.PHONY : compare.i

# target to preprocess a source file
compare.cpp.i:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/compare.cpp.i
.PHONY : compare.cpp.i

compare.s: compare.cpp.s

.PHONY : compare.s

# target to generate assembly for a file
compare.cpp.s:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/compare.cpp.s
.PHONY : compare.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/main.cpp.s
.PHONY : main.cpp.s

types.o: types.cpp.o

.PHONY : types.o

# target to build an object file
types.cpp.o:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/types.cpp.o
.PHONY : types.cpp.o

types.i: types.cpp.i

.PHONY : types.i

# target to preprocess a source file
types.cpp.i:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/types.cpp.i
.PHONY : types.cpp.i

types.s: types.cpp.s

.PHONY : types.s

# target to generate assembly for a file
types.cpp.s:
	$(MAKE) -f CMakeFiles/DDimage.dir/build.make CMakeFiles/DDimage.dir/types.cpp.s
.PHONY : types.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DDimage"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... compare.o"
	@echo "... compare.i"
	@echo "... compare.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... types.o"
	@echo "... types.i"
	@echo "... types.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

